name: check infra

on:
  workflow_call:
    outputs:
      infra-available:
        description: 'If true â€“ AWS credentials are available and we can deploy'
        value: ${{ jobs.check.outputs.infra-available }}

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      infra-available: ${{ steps.set-result.outputs.infra-available }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'eu-central-1' }}

      - name: Mark infra as available
        id: set-result
        run: echo "infra-available=true" >> "$GITHUB_OUTPUT"
