name: check infra

on:
  workflow_call:
    outputs:
      infra-available:
        description: 'If true â€“ AWS is assumed available'
        value: ${{ jobs.check.outputs.infra-available }}

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      infra-available: ${{ steps.set-result.outputs.infra-available }}

    steps:
      - name: Mark infra as available (no AWS check)
        id: set-result
        run: echo "infra-available=true" >> "$GITHUB_OUTPUT"
